# Generated by Django 2.2.3 on 2020-04-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobetrottersGuide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='belong_city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GlobetrottersGuide.City'),
        ),
        migrations.AlterField(
            model_name='review',
            name='belong_country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GlobetrottersGuide.Country'),
        ),
    ]
