# Generated by Django 2.2.3 on 2020-04-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobetrottersGuide', '0002_auto_20200401_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='belong_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GlobetrottersGuide.Country'),
        ),
    ]
