# Generated by Django 2.2.3 on 2020-04-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobetrottersGuide', '0004_auto_20200401_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityreview',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
        migrations.AddField(
            model_name='countryreview',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
    ]
