# Generated by Django 2.2.3 on 2020-04-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobetrottersGuide', '0006_auto_20200404_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Continent',
            new_name='continent',
        ),
    ]
