# Generated by Django 2.2.3 on 2020-04-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobetrottersGuide', '0007_auto_20200404_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='country',
            name='review_count',
        ),
    ]
