# Generated by Django 2.2.3 on 2020-04-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobetrottersGuide', '0009_continent_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_review_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_review_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='review_count',
        ),
    ]
