# Generated by Django 2.2.3 on 2020-04-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobetrottersGuide', '0010_auto_20200408_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GlobetrottersGuide.Country'),
        ),
    ]
